using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sandbox.Logic.Resources.Materials.Minerals;
internal class Class1 {
}


public sealed class OtherChemicals : IChemicalProvider {
	public static IReadOnlyList<Chemical> Chemicals => [
	];
}

public sealed class NativeMinerals : IChemicalProvider {
	public static IReadOnlyList<Chemical> Chemicals => [
	];
}

public sealed class OreMinerals : IChemicalProvider {
	public static IReadOnlyList<Chemical> Chemicals => [
		// Items with valid chemical formulas:
		//new("Quartz", "SiO2"),
		//new("Orthoclase Feldspar", "KAlSi3O8"),
		//new("Albite", "NaAlSi3O8"),
		//new("Anorthite", "CaAl2Si2O8"),
		//new("Microcline", "KAlSi3O8"),
		//new("Biotite", "K(Mg,Fe)3AlSi3O10(F,OH)2"),
		//new("Muscovite", "KAl2(AlSi3O10)(F,OH)2"),
		//new("Lepidolite", "K(Li,Al)3(Al,Si)4O10(F,OH)2"),
		//new("Almandine Garnet", "Fe3Al2(SiO4)3"),
		//new("Pyrope Garnet", "Mg3Al2(SiO4)3"),
		//new("Spessartine Garnet", "Mn3Al2(SiO4)3"),
		//new("Grossular Garnet", "Ca3Al2(SiO4)3"),
		//new("Andradite Garnet", "Ca3Fe2(SiO4)3"),
		//new("Uvarovite Garnet", "Ca3Cr2(SiO4)3"),
		//new("Olivine", "(Mg,Fe)2SiO4"),
		//new("Augite", "Ca(Mg,Fe,Al)(Si,Al)2O6"),
		//new("Diopside", "CaMgSi2O6"),
		//new("Enstatite", "MgSiO3"),
		//new("Wollastonite", "CaSiO3"),
		//new("Tremolite", "Ca2Mg5Si8O22(OH)2"),
		//new("Actinolite", "Ca2(Mg,Fe)5Si8O22(OH)2"),
		//new("Anthophyllite", "Mg7Si8O22(OH)2"),
		//new("Chrysotile", "Mg3Si2O5(OH)4"),
		//new("Lizardite", "Mg3Si2O5(OH)4"),
		//new("Antigorite", "Mg3Si2O5(OH)4"),
		//new("Talc", "Mg3Si4O10(OH)2"),
		//new("Pigeonite", "(Ca,Mg,Fe)Si2O6"),
		//new("Jadeite", "Na(Al,Fe3+)Si2O6"),
		//new("Epidote", "Ca2(Al,Fe)3(SiO4)3(OH)"),
		//new("Zoisite", "Ca2Al3(SiO4)(Si2O7)O(OH)"),
		//new("Scapolite", "(Na,Ca)4Al3(Al,Si)4O12(SO4,Cl)"),
		//new("Nepheline", "Na3K(Al4Si4O16)"),
		//new("Leucite", "KAlSi2O6"),
		//new("Kyanite", "Al2SiO5"),
		//new("Andalusite", "Al2SiO5"),
		//new("Sillimanite", "Al2SiO5"),
		//new("Staurolite", "Fe2Al9Si4O23(OH)"),
		//new("Beryl", "Be3Al2(Si6O18)"),
		//new("Topaz", "Al2SiO4(F,OH)2"),
		//new("Zircon", "ZrSiO4"),
		//new("Sphene (Titanite)", "CaTiSiO5"),
		//new("Mullite", "3Al2O3·2SiO2"),
		//new("Cordierite", "Mg2Al4Si5O18"),
		//new("Omphacite", "(Na,Ca)(Mg,Fe)Si2O6"),
		//new("Rhodonite", "MnSiO3"),
		//new("Dioptase", "CuSiO2(OH)2"),
		//new("Opal", "SiO2·(H2O)"),
		//new("Kaolinite", "Al2Si2O5(OH)4"),
		//new("Prehnite", "Ca2Al(AlSi3O9)(OH)"),
		//new("Calcite", "CaCO3"),
		//new("Aragonite", "CaCO3"),
		//new("Dolomite", "CaMg(CO3)2"),
		//new("Siderite", "FeCO3"),
		//new("Magnesite", "MgCO3"),
		//new("Rhodochrosite", "MnCO3"),
		//new("Smithsonite", "ZnCO3"),
		//new("Otavite", "CdCO3"),
		//new("Witherite", "BaCO3"),
		//new("Strontianite", "SrCO3"),
		//new("Ikaite", "CaCO3·(H2O)6"),
		//new("Gypsum", "CaSO4·(H2O)2"),
		//new("Anhydrite", "CaSO4"),
		//new("Barite", "BaSO4"),
		//new("Celestine", "SrSO4"),
		//new("Anglesite", "PbSO4"),
		//new("Epsomite", "MgSO4·(H2O)7"),
		//new("Kieserite", "MgSO4·(H2O)"),
		//new("Melanterite", "FeSO4·(H2O)7"),
		//new("Glauberite", "Na2Ca(SO4)2"),
		//new("Halite", "NaCl"),
		//new("Sylvite", "KCl"),
		//new("Carnallite", "KMgCl3·(H2O)6"),
		//new("Bischofite", "MgCl2·(H2O)6"),
		//new("Fluorite", "CaF2"),
		//new("Hematite", "Fe2O3"),
		//new("Magnetite", "Fe3O4"),
		//new("Corundum", "Al2O3"),
		//new("Rutile", "TiO2"),
		//new("Anatase", "TiO2"),
		//new("Brookite", "TiO2"),
		//new("Ilmenite", "FeTiO3"),
		//new("Geikielite", "MgTiO3"),
		//new("Spinel", "MgAl2O4"),
		//new("Chromite", "FeCr2O4"),
		//new("Pyrolusite", "MnO2"),
		//new("Cassiterite", "SnO2"),
		//new("Wüstite", "FeO"),
		//new("Periclase", "MgO"),
		//new("Baddeleyite", "ZrO2"),
		//new("Pyrite", "FeS2"),
		//new("Marcasite", "FeS2"),
		//new("Chalcopyrite", "CuFeS2"),
		//new("Sphalerite", "ZnS"),
		//new("Galena", "PbS"),
		//new("Cinnabar", "HgS"),
		//new("Chalcocite", "Cu2S"),
		//new("Covellite", "CuS"),
		//new("Digenite", "Cu9S5"),
		//new("Bornite", "Cu5FeS4"),
		//new("Enargite", "Cu3AsS4"),
		//new("Tetrahedrite", "(Cu,Fe)12Sb4S13"),
		//new("Millerite", "NiS"),
		//new("Pentlandite", "(Fe,Ni)9S8"),
		//new("Pyrrhotite", "FeS"),
		//new("Molybdenite", "MoS2"),
		//new("Arsenopyrite", "FeAsS"),
		//new("Realgar", "As4S4"),
		//new("Orpiment", "As2S3"),
		//new("Stibnite", "Sb2S3"),
		//new("Gold", "Au"),
		//new("Silver", "Ag"),
		//new("Native Copper", "Cu"),
		//new("Platinum", "Pt"),
		//new("Palladium", "Pd"),
		//new("Iridium", "Ir"),
		//new("Osmium", "Os"),
		//new("Rhodium", "Rh"),
		//new("Ruthenium", "Ru"),
		//new("Nickel", "Ni"),
		//new("Graphite", "C"),
		//new("Diamond", "C"),
		//new("Native Sulfur", "S"),
		//new("Native Bismuth", "Bi"),
		//new("Native Antimony", "Sb"),
		//new("Native Arsenic", "As"),
		//new("Apatite", "Ca5(PO4)3(F,Cl,OH)"),
		//new("Monazite", "(Ce,La,Nd,Th)PO4"),
		//new("Xenotime", "YPO4"),
		//new("Turquoise", "CuAl6(PO4)4(OH)8·(H2O)4"),
		//new("Vivianite", "Fe3(PO4)2·(H2O)8"),
		//new("Erythrite", "Co3(AsO4)2·(H2O)8"),
		//new("Vanadinite", "Pb5(VO4)3Cl"),
		//new("Mimetite", "Pb5(AsO4)3Cl"),
		//new("Scheelite", "CaWO4"),
		//new("Wolframite", "(Fe,Mn)WO4"),
		//new("Ulexite", "NaCaB5O6·(H2O)5"),
		//new("Boracite", "Mg3B7O13Cl"),
		//new("Kernite", "Na2B4O6(OH)2·(H2O)3"),
		//new("Goethite", "FeO(OH)"),
		//new("Lepidocrocite", "FeOOH"),
		//new("Malachite", "Cu2CO3(OH)2"),
		//new("Azurite", "Cu3(CO3)2(OH)2"),
		//new("Chrysocolla", "Cu2H2Si2O5(OH)2"),
		//new("Brochantite", "Cu4SO4(OH)6"),
		//new("Atacamite", "Cu2Cl(OH)3"),
		//new("Diaboleite", "Pb2CuCl4(OH)2"),
		//new("Boleite", "K4Cu4PbCl6(OH)6"),
		//new("Stannite", "Cu2FeSnS4"),
		//new("Kesterite", "Cu2ZnSnS4"),
		//new("Hemimorphite", "Zn4Si2O7(OH)2·(H2O)"),
		//new("Cummingtonite", "(Mg,Fe)7Si8O22(OH)2"),
		//new("Lawsonite", "CaAl2Si2O7(OH)2·(H2O)"),
		//new("Glaucophane", "Na2(Mg,Fe)3Al2Si8O22(OH)2"),
		//new("Serandite", "Na2ZrSi6O15·(H2O)3"),
		//new("Eosphorite", "(Mn,Fe)3(PO4)2·(H2O)8"),
		//new("Hedenbergite", "CaFeSi2O6"),
		//new("Paragonite", "NaAl2(AlSi3O10)(OH)2"),
		//new("Margarite", "CaAl2Si2O10(OH)2"),
		//new("Proustite", "Ag3AsS3"),
		//new("Pyrargyrite", "Ag3SbS3"),
		//new("Merwinite", "Ca3Mg(SiO4)2"),
		//new("Ferrosilite", "FeSiO3"),
		//new("Lazurite", "Na8Ca(AlSiO4)6(SO4,S,Cl)2"),
		//new("Hauyne", "Na3Ca(Si3Al3O12)SO4"),
		//new("Sodalite", "Na8(Al6Si6O24)Cl2"),
		//new("Analcime", "NaAlSi2O6·(H2O)"),
		//new("Chrysoberyl", "BeAlO3"),
		//new("Benitoite", "BaTiSi3O9"),
		//new("Jeremejevite", "Al6(BO3)3(OH)3"),
		//new("Pyromorphite", "Pb5(PO4)3Cl"),
		//new("Eudialyte", "Na2CaZr[Si9O27]Cl"),
		//new("Sepiolite", "Mg4Si6O15(OH)2·(H2O)6"),
		//new("Wavellite", "Al3(PO4)2(OH)3·(H2O)5"),
		//new("Tugtupite", "Na4KAl4Si12O30Cl"),
		//new("Danburite", "CaB2(SiO4)2"),
		//new("Zunyite", "(Zr,Al)2Si2O7(OH)2"),
		//new("Sanidine", "KAlSi3O8"),
		//new("Phlogopite", "KMg3(AlSi3O10)(F,OH)2"),
		//new("Clinozoisite", "Ca2Al3(SiO4)(Si2O7)O(OH)"),
		//new("Chrysoprase", "SiO2"),
		//new("Agate", "SiO2"),
		//new("Jasper", "SiO2")
	];
}
//https://en.wikipedia.org/wiki/List_of_minerals